name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install cargo-tauri 
        run: cargo install --force --git https://github.com/I-Info/tauri --branch next
      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use
      - name: build application
        run: pnpm build -d
      
  
  build-darwin-aarch64:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: install cargo-tauri 
        run: cargo install --force --git https://github.com/I-Info/tauri --branch next
        
      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use
      - name: build application
        run: pnpm build -d --target aarch64-apple-darwin

        