name: 'release'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: checkout tauri
        run: git clone https://github.com/I-Info/tauri --branch=next --depth=1
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            tauri/tooling/cli -> tauri/tooling/cli/target
            src-tauri -> src-tauri/target

      - name: install tauri
        run: |
          cd tauri/tooling/cli
          cargo install --path .

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libayatana-appindicator3-dev
      
      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use
      
      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'BingLite v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
      
  
  publish-darwin-aarch64:
    permissions:
      contents: write
    strategy:
      fail-fast: false
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: checkout tauri
        run: git clone https://github.com/I-Info/tauri --branch=next --depth=1
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            tauri/tooling/cli -> tauri/tooling/cli/target
            src-tauri -> src-tauri/target

      - name: install tauri
        run: |
          cd tauri/tooling/cli
          cargo install --path .

      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use
      
      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'BingLite v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: --target aarch64-apple-darwin
    